"""empty message

Revision ID: e2b2ddbdc480
Revises: 
Create Date: 2022-06-14 13:21:28.158620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b2ddbdc480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fias_addres',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ADRESSTYPE', sa.String(length=16), nullable=False),
    sa.Column('ADRESSNAME', sa.String(length=16), nullable=False),
    sa.Column('LEVEL', sa.Integer(), nullable=False),
    sa.Column('STREETCODE', sa.String(length=3), nullable=False),
    sa.Column('POSTALCODE', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('fias_addres_house',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('HOUSENUM', sa.String(length=16), nullable=False),
    sa.Column('HOUSECODE', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('fias_addres_kv',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('KVNUM', sa.String(length=16), nullable=False),
    sa.Column('KVCODE', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('fias_region',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('REGIONCODE', sa.String(length=2), nullable=False),
    sa.Column('REGIONNAME', sa.String(length=36), nullable=False),
    sa.Column('UPDATEDATE', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('STARTDATE', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ENDDATE', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ISACTUAL', sa.Integer(), nullable=False),
    sa.Column('ISACTIVE', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('url_serv', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('url_serv', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_user')
    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('project')
    op.drop_table('post')
    op.drop_table('item')
    op.drop_table('fias_region')
    op.drop_table('fias_addres_kv')
    op.drop_table('fias_addres_house')
    op.drop_table('fias_addres')
    # ### end Alembic commands ###
